# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: WINOTD运动
    url: /#winotd
    weight: 10
  - name: 随笔Flow
    url: /#flow
    weight: 20
  - name: 读后感Reaction
    url: /#reaction
    weight: 30
  - name: 产品Products
    url: /#products
    weight: 40
